config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'about' => 'home#about'
  get 'login' => 'user_sessions#new'

  post 'check' => 'home#check'

  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :packs
  resources :cards do
    get :guessed, on: :collection
  end
  resource :profile, only: [:show, :edit, :update] do
    put :set_current_pack
    put :reset_current_pack
  end
  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :require_login, except: [:index]

  def index
    if current_user.current_pack
      @card = current_user.current_pack.cards.for_review.not_guessed.first
    else
      @card = current_user.cards.for_review.not_guessed.first
    end
  end

  def about
  end

  def check
    @card = Card.find(params[:card_id])
    if @card.check_answer(params[:translated_text])
      flash[:access] = "Верный ответ"
    else
      flash[:danger] = "Ответ неверный или содержит пустое значение"
    end
    redirect_to root_path
  end
end

app/views/home/about.html.erb
<p>Для использования сервиса, пожалуйста, <%= link_to "зарегистрируйтесь", new_user_path %> или <%= link_to "войдите", login_path %>.</p>

<%= image_tag "elements/flashcards.jpg", class: "flashcards" %>

<p>
  Изучение языков в наше время — насущная необходимость для каждого, кто хочет иметь вес в современном обществе. Зная иностранный язык (хотя бы самый распространённый — английский) уже можно расширить границы своих возможностей почти в любой сфере деятельности.
</p>

<p>
  Даже если просто поехать в отпуск в другую страну, знание английского сделает отдых намного комфортнее. Не будет ощущения "я - глухонемой" и можно будет избежать множества проблем. Что же такое язык?
</p>

<p>
  Язык — знаковая система, соотносящая понятийное содержание и типовое звучание (написание). Но это просто сухая терминология. На самом деле, когда находишься в чужой среде знание иностранного языка добавляет новое "шестое" чувство. Вы слышите что-то и понимаете это. Видите надписи и они не выглядят каракулями. И тогда не нужно напрягаться, пытаясь понять, чего от Вас хотят. И это хорошо.
</p>

app/views/home/index.html.erb
<% if @card %>
  <%= form_tag(check_path) do %>
    <div class="row card">
      <div class="col-md-12origin">
        <h2><%= @card.origin_text %></h2>
        <%= image_tag @card.image.url, class: "image" %>
      </div>
      
      <div class="col-md-12 translated">
        <%= text_field_tag :translated_text %>
        <%= hidden_field_tag :card_id, @card.id %>
        <%= submit_tag "Проверить", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% else %>
  <h3>В данный момент нет карточек для изучения.</h3>
<% end %>