config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'about' => 'home#about'
  get 'login' => 'user_sessions#new'

  post 'check' => 'home#check'

  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :packs
  resources :cards do
    get :guessed, on: :collection
  end
  resource :profile, only: [:show, :edit, :update] do
    put :set_current_pack
    put :reset_current_pack
  end
  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create]

end

app/models/pack.rb
class Pack < ActiveRecord::Base
  has_attached_file :image, styles: { original: "360x360>", thumb: "40x40>" },
                            default_url: "/images/:style/missing.png",
                            storage: :s3,
                            s3_credentials: "#{Rails.root}/config/secrets.yml"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes

  validates :name, presence: true

  has_many :cards, dependent: :destroy
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController
  before_action :set_pack, except: [:index, :new, :create, :set_current_pack]

  def index
    @packs = current_user.packs
  end

  def show
    @cards = @pack.cards
  end

  def new
    @pack = Pack.new
  end

  def edit
  end

  def create
    @pack = current_user.packs.new(pack_params)
    if @pack.save
      flash[:access] = "Колода успешно создана"
    else
      flash[:danger] = "Произошла ошибка при добавлении колоды"
    end

    redirect_to packs_path
  end

  def update
    if @pack.update(pack_params)
      flash[:access] = "Колода успешно обновлена"
      redirect_to @pack
    else
      flash[:danger] = "Произошла ошибка при обновлении колоды"
      render 'edit'
    end
  end

  def destroy
    if @pack.destroy
      flash[:access] = "Колода успешно удалена"
    else
      flash[:danger] = "Произошла ошибка при удалении колоды"
    end

    redirect_to packs_path
  end

  private
    def set_pack
      @pack = current_user.packs.find(params[:id])
    end

    def pack_params
      params.require(:pack).permit(:name, :image)
    end
end

app/views/packs/_form.html.erb
<%= bootstrap_form_for @pack do |f| %>
  <%= f.text_field :name, label: "Название колоды" %>
  <%= f.file_field :image, label: "Изображение" %>
  <%= f.submit "Сохранить", class: "btn btn-success" %>
  <%= link_to "Назад", packs_path, class: "btn btn-default" %>
<% end %>

app/views/packs/edit.html.erb
<h1>Редактировать колоду</h1>

<%= render 'form' %>

app/views/packs/index.html.erb
<div class="row">
  <ul class="nav nav-pills">
    <li><%= link_to "Добавить колоду", new_pack_path, id: "new_pack" %></li>
    <li><%= link_to "Сбросить колоды", reset_current_pack_profile_path, id: "reset", method: "put" %></li>
  </ul>
  
  <table class="table">
    <tr>
      <td><b>Изображение</b></td>
      <td><b>Название</b></td>
      <td><b>Количество карточек</b></td>
      <td><b>Действия</b></td>
    </tr>

    </div>
      <% @packs.each do |pack| %>
        <tr class="<%= pack == current_user.current_pack ? 'current-pack' : 'inactive-pack' %>">
            <td><%= image_tag pack.image.url(:thumb) %></td>
            <td><%= pack.name %></td>
            <td><%= pack.cards.count %></td>
            <td><%= link_to "Выбрать", set_current_pack_profile_path(pack_id: pack.id), class: "btn btn-success", method: "put" %></td>
            <td><%= link_to "Просмотр", pack, class: "btn btn-primary" %></td>
            <td><%= link_to "Редактировать", edit_pack_path(pack), class: "btn btn-warning", id: "edit-pack" %></td>
            <td><%= link_to "Удалить", pack, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger", id: "delete-pack" %></td>
          </tr>
      <% end %>
    </div>
  </table>
</div>

app/views/packs/new.html.erb
<h1>Новая колода</h1>

<%= render 'form' %>

app/views/packs/show.html.erb
<div class="row">
  <ul class="nav nav-pills">
    <li><%= link_to "Добавить карточку", new_card_path,  id: "add_button" %></li>
  </ul>
  <table class="table">
    <tr>
      <td><b>Изображение</b></td>
      <td><b>Оригинальный текст</b></td>
      <td><b>Перевод</b></td>
      <td><b>Дата просмотра</b></td>
      <td><b>Действия</b></td>
    </tr>
    </div>
      <% @cards.each do |card| %>
        <tr>
          <td><%= image_tag card.image.url(:thumb) %></td>
          <td><%= card.origin_text %></td>
          <td><%= card.translated_text %></td>
          <td><%= card.review_date.strftime("%d/%m/%y") %></td>
          <td><%= link_to "Просмотр", card, class: "btn btn-primary" %></td>
          <td><%= link_to "Редактировать", edit_card_path(card), class: "btn btn-warning", id: "edit_card" %></td>
          <td><%= link_to "Удалить", card, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger", id: "delete_card" %></td>
        </tr>
      <% end %>
    </table>
</div>
<%= link_to "Назад", packs_path, class: "btn btn-default" %>