config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'about' => 'home#about'
  get 'login' => 'user_sessions#new'

  post 'check' => 'home#check'

  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :packs
  resources :cards do
    get :guessed, on: :collection
  end
  resource :profile, only: [:show, :edit, :update] do
    put :set_current_pack
    put :reset_current_pack
  end
  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create]

end

app/models/card.rb
class Card < ActiveRecord::Base
  before_save :lowercase_translated_text
  before_create :set_default_review_date

  has_attached_file :image, styles: { original: "360x360>", thumb: "40x40>" },
                            default_url: "/images/:style/missing.png",
                            storage: :s3,
                            s3_credentials: "#{Rails.root}/config/secrets.yml"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes

  validates :origin_text, :translated_text, :user_id, :pack_id, presence: true

  scope :for_review, -> { where('review_date <= ?', Date.today).order("RANDOM()") }
  scope :guessed, -> { where(guessed: true) }
  scope :not_guessed, -> { where(guessed: false) }

  belongs_to :user
  belongs_to :pack

  def check_answer(answer)
    if answer.mb_chars.downcase == translated_text && wrong_repetition_count < 3
      set_right_answer
      true
    elsif answer.mb_chars.downcase != translated_text && wrong_repetition_count < 2
      increment_wrong_answers_count
      false
    else
      reset_review_date
      false
    end
  end

  def set_right_answer
    case right_repetition_count
    when 0
      update(review_date: Date.today + 1.day)
    when 1
      update(review_date: Date.today + 3.days)
    when 2
      update(review_date: Date.today + 1.week)
    when 3
      update(review_date: Date.today + 2.weeks)
    when 4
      update(review_date: Date.today + 1.month)
    else
      update(guessed: true)
    end
    increment!(:right_repetition_count, 1)
  end

  def increment_wrong_answers_count
    increment!(:wrong_repetition_count, 1)
  end

  def reset_review_date
    update(review_date: Date.today + 1.day, wrong_repetition_count: 0)
  end

  def lowercase_translated_text
    self.translated_text = translated_text.mb_chars.downcase
  end

  def set_default_review_date
    self.review_date = DateTime.now
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, except: [:index, :new, :create, :guessed]

  def index
    @cards = current_user.cards.not_guessed
  end

  def show
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = current_user.cards.new(card_params)
    if @card.save
      flash[:access] = "Карточка успешно создана"
    else
      flash[:danger] = "Произошла ошибка при добавлении карточки"
    end

    redirect_to @card
  end

  def update
    if @card.update(card_params)
      flash[:access] = "Карточка успешно обновлена"
      redirect_to @card
    else
      flash[:danger] = "Произошла ошибка при обновлении карточки"
      render 'edit'
    end
  end

  def destroy
    if @card.destroy
      flash[:access] = "Карточка успешно удалена"
    else
      flash[:danger] = "Произошла ошибка при удалении карточки"
    end

    redirect_to cards_path
  end

  def guessed
    @cards = current_user.cards.guessed
  end

  private
    def set_card
      @card = current_user.cards.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:origin_text, :translated_text, :pack_id, :image)
    end
end

app/views/cards/_form.html.erb
<%= bootstrap_form_for @card do |f| %>
  <%= select("card", "pack_id", current_user.packs.collect {|p| [ p.name, p.id ] }, {include_blank: 'Выберите колоду'}) %>
  <%= f.text_field :origin_text, label: "Оригинальный текст" %>
  <%= f.text_field :translated_text, label: "Перевод" %>
  <%= f.file_field :image, label: "Изображение" %>
  <%= f.submit "Сохранить", class: "btn btn-success" %>
  <%= link_to "Назад", cards_path, class: "btn btn-default" %>
<% end %>

app/views/cards/_table.html.erb
<div class="row">
  <ul class="nav nav-pills">
    <li><%= link_to "Добавить карточку", new_card_path, id: "new_card" %></li>
    <li><%= link_to "Отгаданные", guessed_cards_path %></li>
  </ul>
</div>
<div class="row">
  <table class="table">
    <tr>
      <td><b>Изображение</b></td>
      <td><b>Оригинальный текст</b></td>
      <td><b>Перевод</b></td>
      <td><b>Дата просмотра</b></td>
      <td><b>Действия</b></td>
    </tr>
    <% @cards.each do |card| %>
      <tr>
        <td><%= image_tag card.image.url(:thumb) %></td>
        <td><%= card.origin_text %></td>
        <td><%= card.translated_text %></td>
        <td><%= card.review_date.strftime("%d/%m/%y") %></td>
        <td><%= link_to "Просмотр", card, class: "btn btn-primary" %></td>
        <td><%= link_to "Редактировать", edit_card_path(card), class: "btn btn-warning", id: "edit_card" %></td>
        <td><%= link_to "Удалить", card, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger", id: "delete_card" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/cards/edit.html.erb
<h1>Редактировать карточку</h1>

<%= render 'form' %>

app/views/cards/guesed.html.erb
<%= render 'table' %>

app/views/cards/guessed.html.erb
<%= render 'table' %>

app/views/cards/index.html.erb
<%= render 'table' %>

app/views/cards/new.html.erb
<h1>Новая карточка</h1>

<%= render 'form' %>

app/views/cards/show.html.erb
<div id="row">
  <table class="table">
    <tr>
      <td><b>Оригинальный текст</b></td>
      <td><%= @card.origin_text %></td>
    </tr>
    <tr>
      <td><b>Перевод</b></td>
      <td><%= @card.translated_text %></td>
    </tr>
    <tr>
      <td><b>Дата просмотра</b></td>
      <td><%= @card.review_date.strftime("%d/%m/%y") %></td>
    </tr>
      <td><b>Создано</b></td>
      <td><%= @card.created_at.strftime("%d/%m/%y - %H:%M:%S") %></td>
    <tr>
      <td><b>Обновлено</b></td>
      <td><%= @card.updated_at.strftime("%d/%m/%y - %H:%M:%S") %></td>
    </tr>
  </table>
  <%= link_to "Назад", cards_path, class: "btn btn-default" %>
</div>