config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'about' => 'home#about'
  get 'login' => 'user_sessions#new'

  post 'check' => 'home#check'

  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :packs
  resources :cards do
    get :guessed, on: :collection
  end
  resource :profile, only: [:show, :edit, :update] do
    put :set_current_pack
    put :reset_current_pack
  end
  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create]

end

app/views/layouts/_footer.html.erb
<footer>
	<p>Powered by <%= link_to "Vitaliy Fry", "https://github.com/Frylock13" %></p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="row">
    <div class="col-md-4 logo">
      <%= link_to (image_tag "elements/logo.png" ), root_path %>
    </div>
    
    <div class="col-md-8 header-nav">
      <ul class="nav nav-pills">
        <% if current_user %>
          <li><%= link_to "Главная", root_path %></li>
          <li><%= link_to "Колоды", packs_path %></li>
          <li><%= link_to "Карточки", cards_path %></li>
          <li><%= link_to "Профиль", profile_path %></li>
          <li><%= link_to "Выйти", :logout, method: :delete %></li>
        <% else %>
          <li><%= link_to "Главная", root_path %></li>
          <li><%= link_to "Войти", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Флэшкарточкер</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <section class="container-fluid">

    <%= render 'layouts/header' %>

    <section>
      <div class="row">
        <div class="col-md-12 content">
          <% flash.each do |type, message| %>
            <h3>
              <div class="alert <%= flash_class type %>">
                <%= message %>
              </div>
            </h3>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </section>

    <%= render 'layouts/footer' %>

  </section>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
   $('.alert').fadeOut(2000);
  });
</script>

</body>
</html>